jadwal/urls.py
from django.urls import path
from . import views

app_name = 'jadwal'

urlpatterns = [
    path('buat-jadwal', views.buat_jadwal, name='buat-jadwal'),
    path('isi-jadwal/<str:url>', views.isi_jadwal, name='isi-jadwal'),
    path('invite/<str:url>', views.invite, name='invite'),
    path('<str:url>', views.jadwal, name='jadwal'),
]

komentar/urls.py
from django.urls import path
from . import views

app_name = 'komentar'

urlpatterns = [
    path('<str:judul>', views.index_komentar, name='index_komentar'),
    path('tambah_komentar/<str:judul>/<str:name>', views.tambah_komentar, name='tambah_komentar'),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

ppwtk1/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('userhandle/', include('userhandle.urls')),
    path('komentar/', include('komentar.urls')),
    path('jadwal/', include('jadwal.urls')),
    path('', include('main.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('feedback/', include('umpanbalik.urls')),
]

jadwal/models.py
from django.db import models
from django.core.exceptions import ValidationError
from userhandle.models import MyUser

class Jadwal(models.Model):
    judul = models.CharField(max_length=50)
    url = models.CharField(editable=False, max_length=40)
    tanggal_awal = models.DateField()
    tanggal_akhir = models.DateField()
    owner_id = models.IntegerField()
    users = models.ManyToManyField(MyUser)
    
    def clean(self):
        if self.tanggal_awal and self.tanggal_akhir:
            if self.tanggal_awal > self.tanggal_akhir:
                raise ValidationError("Tanggal awal tidak boleh mulai setelah Tanggal akhir")
    
    def __str__(self):
        return self.judul
                
class Tanggal(models.Model):
    jadwal = models.ForeignKey('Jadwal', on_delete=models.CASCADE)
    tanggal = models.DateField()
    
class Kegiatan(models.Model):
    user = models.ForeignKey('userhandle.MyUser', on_delete=models.CASCADE)
    jadwal = models.ForeignKey('Jadwal', on_delete=models.CASCADE)
    tanggal = models.ForeignKey('Tanggal', on_delete=models.CASCADE)
    bisa = models.BooleanField(default=False)
    jam_awal = models.TimeField()

jadwal/forms.py
from django import forms
from django.core.exceptions import ValidationError
from jadwal.models import Jadwal, Kegiatan

class JadwalForm(forms.ModelForm):
    class Meta:
        model = Jadwal
        fields = ['judul', 'tanggal_awal', 'tanggal_akhir']
        
    judul = forms.CharField(label="", widget=forms.TextInput(
        attrs = {
                    'class' : 'form-input',
                    'placeholder' : 'Judul Rapat',
                    'required' : 'required'
                }
    ))
    
    tanggal_awal = forms.DateField(label="", input_formats=["%d/%m/%Y"], widget=forms.DateInput(
        attrs = {
                    'type' : 'text',
                    'class' : 'form-input',
                    'placeholder' : 'Tanggal awal',
                    'required' : 'required',
                    'onfocus' : 'dateInputFocus(this)',
                    'onblur' : 'dateInputBlur(this)'
                }
    ))
    
    tanggal_akhir = forms.DateField(label="", input_formats=["%d/%m/%Y"], widget=forms.DateInput(
        attrs = {
                    'type' : 'text',
                    'class' : 'form-input',
                    'placeholder' : 'Tanggal akhir',
                    'required' : 'required',
                    'onfocus' : 'dateInputFocus(this)',
                    'onblur' : 'dateInputBlur(this)'
                }
    ))
    
    def validate(self):
        cleaned_data = super().clean()
        tanggal_awal = cleaned_data.get("tanggal_awal")
        tanggal_akhir = cleaned_data.get("tanggal_akhir")

        if tanggal_awal and tanggal_akhir:
            if tanggal_awal > tanggal_akhir:
                raise ValidationError("Tanggal awal tidak boleh mulai setelah Tanggal akhir")
    
class AnggotaForm(forms.Form):
    nama = forms.CharField(label="", widget=forms.TextInput(
        attrs = {
                    'class' : 'form-input',
                    'placeholder' : 'Tambah Anggota'
                }
    ))

class JoinForm(forms.Form):
    join = forms.BooleanField(label="", initial=True, widget=forms.HiddenInput(attrs = {'readonly' : True}))
    
class IsiJadwalForm(forms.Form):
    kegiatan_id = forms.IntegerField(label="", widget=forms.HiddenInput())
    bisa = forms.BooleanField(label="", widget=forms.CheckboxInput(attrs = {'hidden' : True}))

jadwal/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
from .forms import JadwalForm, JoinForm, IsiJadwalForm
from .models import Jadwal, Tanggal, Kegiatan
from userhandle.models import MyUser
from babel.dates import format_date
import string, secrets, datetime

BASE64 = []
TIMESTAMPS = []

def init():
    global BASE64
    global TIMESTAMPS
    
    BASE64 = list(string.ascii_uppercase + string.ascii_lowercase + string.digits + '-' + '_')
    
    for i in range(8, 22):
        TIMESTAMPS.append(datetime.time(hour=i).strftime('%H:%M'))

def date_range(awal, akhir):
    for day_count in range(int((akhir - awal).days) + 1):
        yield awal + datetime.timedelta(day_count)
        
init()

### BUAT JADWAL ###
def buat_jadwal(request):
    if (not request.user.is_authenticated):
        return HttpResponseRedirect('/userhandle/login')
    context = {}
    
    jadwal_form = JadwalForm(request.POST or None)
    
    if request.method == "POST":
        if jadwal_form.is_valid():
            owner = MyUser.objects.get(username=request.user)
            if owner:
                if owner.is_active:
                    ''' PROCESS JADWAL '''
                    jadwal = jadwal_form.save(commit=False)
                    
                    jadwal.owner_id = owner.id
                    
                    random = secrets.SystemRandom()
                    while True:
                        try:
                            url = ''.join(random.sample(BASE64, 40))
                            Jadwal.objects.get(url=url)
                        except Jadwal.DoesNotExist:
                            break
                    jadwal.url = url
                    
                    jadwal.save()
                    jadwal.users.add(owner)

                    ''' PROCESS TANGGAL & KEGIATAN '''     
                    dates = []
                    awal = jadwal.tanggal_awal
                    akhir = jadwal.tanggal_akhir
                    for date in date_range(awal, akhir):
                        tanggal = Tanggal(jadwal=jadwal, tanggal=date) 
                        tanggal.save()
                        
                        for hour in range(8, 21):
                            kegiatan = Kegiatan(user=owner, jadwal=jadwal, tanggal=tanggal, jam_awal=datetime.time(hour=hour))
                            kegiatan.save()
                    
                    return HttpResponseRedirect("/jadwal/" + url)
        else:
            context['jadwal_form'] = jadwal_form
    else:
        context['jadwal_form'] = JadwalForm()
    
    return render(request, 'jadwal/buat-jadwal.html', context)
 
### INVITE ### 
def invite(request, url):
    context = {}
    
    jadwal = Jadwal.objects.get(url=url)
    context['jadwal'] = jadwal      
    
    if request.method == "POST":
        if not request.user.is_authenticated:
            return HttpResponseRedirect('/userhandle/login')
        user = request.user
        join = JoinForm(request.POST)
        if join.is_valid():
            try:
                jadwal.users.get(username=user.username)
            except MyUser.DoesNotExist:
                if user.id != jadwal.owner_id:
                    jadwal.users.add(user)
                    
                    awal = jadwal.tanggal_awal
                    akhir = jadwal.tanggal_akhir
                    for date in date_range(awal, akhir):
                        tanggal = Tanggal.objects.get(jadwal=jadwal, tanggal=date)
                        
                        for hour in range(8, 21):
                            kegiatan = Kegiatan(user=user, jadwal=jadwal, tanggal=tanggal, jam_awal=datetime.time(hour=hour))
                            kegiatan.save()
            return HttpResponseRedirect("/jadwal/" + jadwal.url)
            
    context['join'] = JoinForm()
        
    return render(request, 'jadwal/invite.html', context)

### JADWAL ###
def jadwal(request, url):
    context = {}

    context['TS'] = TIMESTAMPS
    
    jadwal = Jadwal.objects.get(url=url)
    context['jadwal'] = jadwal

    if (not request.user.is_authenticated) or (request.user not in jadwal.users.all()):
        return HttpResponseRedirect('/')
    
    owner = MyUser.objects.get(id=jadwal.owner_id)
    context['owner'] = owner
    
    users = []
    for user in jadwal.users.all():
        if user != owner:
            users.append(user)
    context['users'] = users
    
    user = MyUser.objects.get(username=request.user)
    if user:
        if user.is_active:
            dates = dict()
            for date in Tanggal.objects.filter(jadwal=jadwal):
                tanggal = format_date(date.tanggal, "EEEE, dd/MM/yy", locale="id")
                kegiatan_count = []
                for hour in range(8, 21):
                    kegiatan_count.append(Kegiatan.objects.filter(jadwal=jadwal, tanggal=date, bisa=True, jam_awal=datetime.time(hour=hour)).count())
                dates[tanggal] = kegiatan_count
            context['dates'] = dates
            
    return render(request, 'jadwal/jadwal.html', context)
  
### ISI JADWAL ###  
def isi_jadwal(request, url):
    context = {}
    
    context['TS'] = TIMESTAMPS
    
    jadwal = Jadwal.objects.get(url=url)
    context['jadwal'] = jadwal
    
    if (not request.user.is_authenticated) or (request.user not in jadwal.users.all()):
        return HttpResponseRedirect('/')
    
    owner = MyUser.objects.get(id=jadwal.owner_id)
    context['owner'] = owner
    
    users = []
    for user in jadwal.users.all():
        if user != owner:
            users.append(user)
    context['users'] = users
    
    user = MyUser.objects.get(username=request.user)
    if user:
        if user.is_active:
            dates = dict()
            for date in Tanggal.objects.filter(jadwal=jadwal):
                tanggal = format_date(date.tanggal, "EEEE, dd/MM/yy", locale="id")
                kegiatan = []
                for hour in range(8, 21):
                    kegiatan_count = Kegiatan.objects.filter(jadwal=jadwal, tanggal=date, bisa=True, jam_awal=datetime.time(hour=hour)).count()
                    my_kegiatan = Kegiatan.objects.get(user=user, jadwal=jadwal, tanggal=date, jam_awal=datetime.time(hour=hour))
                    
                    form_prefix = str(my_kegiatan.id)
                    my_kegiatan_form = IsiJadwalForm(prefix=form_prefix, initial={'kegiatan_id' : my_kegiatan.id, 'bisa' : my_kegiatan.bisa})
                    
                    kegiatan.append((kegiatan_count, my_kegiatan_form))
                dates[tanggal] = kegiatan
            context['dates'] = dates
    
    if request.method == "POST":
        for key, value in request.POST.items():
            args = key.split('-')
            if len(args) > 1 and args[1] == "kegiatan_id":
                kegiatan_id = int(args[0])
                if request.POST.get(args[0] + "-bisa", False):
                    Kegiatan.objects.filter(id=kegiatan_id).update(bisa=True)
                else:
                    Kegiatan.objects.filter(id=kegiatan_id).update(bisa=False)
                    
        return HttpResponseRedirect(reverse('jadwal:jadwal', args=[jadwal.url]))
            
    return render(request, 'jadwal/isi-jadwal.html', context)

jadwal/templates/jadwal/buat-jadwal.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<title>Buat Jadwal</title>
<link rel="stylesheet" href="{% static 'jadwal/css/style.css' %}">
<script src="{% static 'jadwal/js/script.js' %}"></script>
{% endblock head %}

{% block content %}
<section class="d-flex flex-column" style="padding: 10vmin;">
    <div class="form-container">
        <div class="form-jadwal px-3 py-4">
            <div class="hint mb-3">Isi detail rapat di sini</div>
            <form action="" method="POST">
                {% csrf_token %}
                <div id="detail-jadwal" class="d-flex flex-column">
                    <p>{{ jadwal_form.judul }}</p>
                    <div class="form-tanggal">
                        <p>{{ jadwal_form.tanggal_awal }}</p>
                        <p>{{ jadwal_form.tanggal_akhir }}</p>
                    </div>
                    <p>{{ anggota_form.nama }}</p>
                </div>
                {% if jadwal_form.errors %}
                    {% for error in jadwal_form.non_field_errors %}
                        <div class="alert alert-danger">
                            <strong>{{ error|escape }}</strong>
                        </div>
                    {% endfor %}
                {% endif %}
                <input class="py-1 px-2 mt-2 my-btn" type="submit" value="Jadwalkan Rapat">
            </form>
        </div>
            <!-- TODO : Make background image position similar to prototype-->
            <!-- Sesiapa saja, tolongin :') -->
            <img src="{% static 'jadwal/img/youngpeople 1.png' %}" class="d-none d-lg-block" style="border-radius: 25px;">
    </div>
</section>
{% endblock content %}

jadwal/templates/jadwal/invite.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<title>Undangan</title>
<link rel="stylesheet" href="{% static 'jadwal/css/style.css' %}">
<script src="{% static 'jadwal/js/script.js' %}"></script>
{% endblock head %}

{% block content %}
<section class="d-flex flex-column h-100">
    <div class="m-auto">
        <div class="invite-text d-flex flex-column align-items-center">
            <div>Anda telah diundang ke rapat</div>
            <div>{{ jadwal.judul }}</div>
        </div>
        <div class="d-flex justify-content-center pt-5">
            <form action="{% url 'jadwal:invite' jadwal.url %}" method="POST">
                {% csrf_token %}
                {{ join }}
                <button class="my-btn px-5 py-3" type="submit">Gabung Sekarang</button>
            </form>
        </div>
    </div>
</section>
{% endblock content %}

jadwal/templates/jadwal/isi-jadwal.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<title>{{ jadwal.judul }}</title>
<link rel="stylesheet" href="{% static 'jadwal/css/style.css' %}">
<script src="{% static 'jadwal/js/script.js' %}"></script>
{% endblock head %}

{% block content %}
<form action="" method="POST">
    {% csrf_token %}
    <section class="d-flex">
            <div class="d-flex w-100 jadwal-container">
                <div class="timestamps">
                {% for time in TS %}
                    <div class="timestamp">{{ time }}</div>
                {% endfor %}
                </div>
                    <div class="dates">
                    {% for date, blocks in dates.items %}
                        <div class="date">
                            <div class="format">
                            {{ date }}
                            </div>
                            <div class="blocks">
                            {% for count, kegiatan_form in blocks %}
                                <div class="block {% if count != 0 %}bg-blue{% endif %}" onclick="checkboxHandler(this)">
                                    <div class="{% if count == 0 %}invisible{% endif %}">
                                        {{ kegiatan_form }}
                                        <span><span id="counter">{{ count }}</span> orang bisa</span>
                                    </div>
                                </div>
                            {% endfor %}
                            </div>
                        </div>
                    {% endfor %}
                    </div>
            </div>
        <div class="right-sidebar">
            <div class="d-flex flex-column p-2">
                <div class="judul">{{ jadwal.judul }}</div>
                <div>
                    <!--span>Pemilik:</span-->
                    <div class="block nama justify-content-start">
                    {{ owner.nama_panjang }}
                    </div>
                    <!--span>Anggota:</span-->
                    {% if users %}
                    {% for user in users %}
                    <div class="block nama justify-content-start">
                    {{ user.nama_panjang }}
                    </div>
                    {% endfor %}
                    {% else %}
                    <!--div class="text-center">(kosong)</div-->
                    {% endif %}
                </div>
                <div class="d-flex flex-row-reverse flex-shrink-1">
                    <button class="my-btn" onclick="copyInvitationalLink('{{ request.META.HTTP_HOST }}', '{% url 'jadwal:invite' jadwal.url %}')">Undang Anggota</button>
                </div>
                <div id="copy-success" class="text-center invisible">
                    Undangan berhasil disalin
                </div>
            </div>
            <div class="options">
                <div><input type="submit" class="my-btn w-100" value="Simpan Jadwal"></input></div>
            <div>
            </div>
        </div>
    </section>
</form>
{% endblock content %}

jadwal/templates/jadwal/jadwal.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<title>{{ jadwal.judul }}</title>
<link rel="stylesheet" href="{% static 'jadwal/css/style.css' %}">
<script src="{% static 'jadwal/js/script.js' %}"></script>
{% endblock head %}

{% block content %}
<section class="d-flex">
    <div class="d-flex w-100 jadwal-container">
        <div class="timestamps">
        {% for time in TS %}
            <div class="timestamp">{{ time }}</div>
        {% endfor %}
        </div>
        <div class="dates">
        {% for date, counts in dates.items %}
            <div class="date">
                <div class="format">
                {{ date }}
                </div>
                <div class="blocks">
                {% for count in counts %}
                    <div class="block {% if count != 0 %}bg-blue{% endif %}">
                        <div class="{% if count == 0 %}invisible{% endif %}">{{ count }} orang bisa</div>
                    </div>
                {% endfor %}
                </div>
            </div>
        {% endfor %}
        </div>
    </div>
    <div class="right-sidebar">
        <div class="d-flex flex-column p-2">
            <div class="judul">{{ jadwal.judul }}</div>
            <div>
                <!--span>Pemilik:</span-->
                <div class="block nama justify-content-start">
                {{ owner.nama_panjang }}
                </div>
                <!--span>Anggota:</span-->
                {% if users %}
                {% for user in users %}
                    {% if not user is owner %}
                    <div class="block nama justify-content-start">
                    {{ user.nama_panjang }}
                    </div>
                    {% endif %}
                {% endfor %}
                {% else %}
                <!--div class="text-center">(kosong)</div-->
                {% endif %}
            </div>
            <div class="d-flex flex-row-reverse">
                <button class="my-btn" onclick="copyInvitationalLink('{{ request.META.HTTP_HOST }}', '{% url 'jadwal:invite' jadwal.url %}')">Undang Anggota</button>
            </div>
            <div id="copy-success" class="text-center invisible">
                Undangan berhasil disalin
            </div>
        </div>
        <div class="options">
            <div><a href="{% url 'komentar:index_komentar' jadwal.judul %}" class="my-btn">Beri Komentar</a></div>
            <div><a href="{% url 'jadwal:isi-jadwal' jadwal.url %}" class="my-btn">Isi Jadwal</a></div>
        <div>
        </div>
    </div>
</section>
{% endblock content %}