main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

ppwtk1/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('userhandle/', include('userhandle.urls')),
    path('komentar/', include('komentar.urls')),
    path('jadwal/', include('jadwal.urls')),
    path('', include('main.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('feedback/', include('umpanbalik.urls')),
]

umpanbalik/urls.py
from django.urls import path
from . import views
 
app_name = 'umpanbalik'

urlpatterns = [
    path('list', views.list, name='list'),
    path('create', views.create, name='create'),
    path('edit/<str:id>', views.edit, name='edit'),
]

umpanbalik/models.py
from django.db import models

# Create your models here.
class Feedback(models.Model):
    """docstring for Feedback."""
    comment = models.TextField()
    createDate = models.DateTimeField(auto_now_add=True, blank=True)

umpanbalik/forms.py
from django import forms
from .models import Feedback

class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        fields = ['comment']

umpanbalik/views.py
from django.shortcuts import render, redirect
from .models import *
from .forms import FeedbackForm
 
def list(request):
    feedbacks = Feedback.objects.all()
    return render(request, 'feedbacklist.html', {'feedbacks': feedbacks})
 
def create(request):
    if request.method=='POST':
        form = FeedbackForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('/feedback/list')
    else:
        form = FeedbackForm()
 
    return render(request, 'feedback.html', {'form': form})
 
def edit(request, id):
    fb = Feedback.objects.get(pk=id)
    if request.method=='POST':
        form = FeedbackForm(request.POST, instance=fb)
        if form.is_valid():
            form.save()
        return redirect('/feedback/list')
    else:
        form = FeedbackForm(instance=fb)
 
    return render(request, 'feedback.html', {'form': form})

umpanbalik/templates/feedback.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<title>Feedback</title>
{% endblock head %}

{% block content %}
<div class="container">
    <div class="form">
        <h2>Feedback</h2>
        <p>
            <a href="{% url 'umpanbalik:list' %}">Lihat List</a>
        </p>
        <div>
            <form method="POST">
                {% csrf_token %}
                <table class="table">
                    {{ form.as_table }}
                </table>
                <button type="submit">Kirim</button>
                <span></span>
                <span></span>
                <span></span>
                <input type="checkbox" id="statement" name="state1">
                <label for="state1">Kirim Sebagai Anonymous</label>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

umpanbalik/templates/feedbacklist.html
{% extends "base.html" %}
{% load static %}

{% block head %}
    <title>Feedback List</title>
{% endblock head %}

{% block content %}
    <h3>
        Feedback List
    </h3>
    <p>
        <a href="{% url 'umpanbalik:create' %}">+ Create New</a>
    </p>

    <table class="table">
        <tr><th>Id</th><th>Tulis Pesan Anda</th></tr>
        {% for item in feedbacks %}
            <tr>
                <td>
                    <a href="{% url 'umpanbalik:edit' id=item.id %}">{{ item.id }}</a>
                </td>
                <td>{{ item.comment }}</td>
            </tr>
        {% endfor %}
    </table>
{% endblock content %}