dashboard/urls.py
from django.urls import path
from . import views

app_name = "dashboard"

urlpatterns = [
    path('', views.indexDashboard, name='indexDashboard'),
    path('hapus-jadwal/<str:url>', views.hapusJadwal, name='hapusJadwal'),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

ppwtk1/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('userhandle/', include('userhandle.urls')),
    path('komentar/', include('komentar.urls')),
    path('jadwal/', include('jadwal.urls')),
    path('', include('main.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('feedback/', include('umpanbalik.urls')),
]

userhandle/urls.py
from django.urls import path

from .views import login, logout, register

app_name = 'userhandle'

urlpatterns = [
    path('login', login, name='login'),
    path('logout', logout, name='logout'),
    path('register', register, name='register'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    {% block head %}{% endblock %}

</head>
<body>
    <nav class="navbar navbar-expand-md navbar-custom d-flex justify-content-between">
        <a class="navbar-brand" href="{% url 'main:home' %}">JadwalinAja</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                <li class="nav-item"><div class="nav-label">Hi, {{ user.nama_panjang }}</div></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'dashboard:indexDashboard' %}">Dashboard</a></li> <!--  TODO: supposed to be directed to dashboard -->
                <li class="nav-item"><a class="nav-link" href="{% url 'userhandle:logout' %}">Log Out</a></li>
                {% else %}
                <li class="nav-item"><a class="nav-link" href="{% url 'userhandle:register' %}">Register</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'userhandle:login' %}">Log In</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>

	{% block content %}{% endblock %}
</body>
</html>