dashboard/urls.py
from django.urls import path
from . import views

app_name = "dashboard"

urlpatterns = [
    path('', views.indexDashboard, name='indexDashboard'),
    path('hapus-jadwal/<str:url>', views.hapusJadwal, name='hapusJadwal'),
]

jadwal/urls.py
from django.urls import path
from . import views

app_name = 'jadwal'

urlpatterns = [
    path('buat-jadwal', views.buat_jadwal, name='buat-jadwal'),
    path('isi-jadwal/<str:url>', views.isi_jadwal, name='isi-jadwal'),
    path('invite/<str:url>', views.invite, name='invite'),
    path('<str:url>', views.jadwal, name='jadwal'),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

ppwtk1/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('userhandle/', include('userhandle.urls')),
    path('komentar/', include('komentar.urls')),
    path('jadwal/', include('jadwal.urls')),
    path('', include('main.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('feedback/', include('umpanbalik.urls')),
]

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/views.py
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from jadwal.models import Jadwal
from userhandle.models import MyUser
import datetime

def indexDashboard(request):
    if not request.user.is_authenticated:
        return redirect('userhandle:login')
    schedules = []
    owners = []
    user_counts = []
    for jadwal in Jadwal.objects.all():
        if request.user in jadwal.users.all():
            schedules.append(jadwal)
            owners.append(MyUser.objects.get(pk=jadwal.owner_id))
            user_counts.append(jadwal.users.all().count())
    schedules_zip = zip(schedules, owners, user_counts)
    if schedules:
        ada_jadwal = True
    else:
        ada_jadwal = False
    return render(request, 'dashboard.html', {'schedules': schedules_zip, 'ada_jadwal': ada_jadwal})

def hapusJadwal(request, url):
    if (request.method == 'POST'):
        jadwal = get_object_or_404(Jadwal, url=url)
        messages.success(request, f'Jadwal {jadwal} has been deleted!')
        jadwal.delete()
    return HttpResponseRedirect('/dashboard')

dashboard/templates/dashboard.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'dashboard/css/style-dashboard.css' %}">
<title>Jadwal Saya</title>
{% endblock head %}

{% block content %}
<div class="content p-5">
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
            {{ message }}
        </div>
    {% endfor %}
    <div class="jadwal mx-auto">
        <div class="header ml-3 mb-3"><h1>Jadwal Saya</h1></div>
        {% if ada_jadwal %}
            <div class="table">
                {% for schedule,owner,user_count in schedules %}
                <div class="card m-3">
                    <h5 class="card-header"><b>{{ schedule }}</b></h5>
                    <div class="card-body">
                        {% if owner == user %}
                            <p>Owner: Anda</p>
                        {% else %}
                            <p>Owner: {{ owner.nama_panjang }}</p>
                        {% endif %}
                        <p>Ada {{ user_count }} orang yang tergabung dalam rapat ini.</p>
                        <a href="{% url 'jadwal:jadwal' schedule.url %}" class="btn btn-primary">Buka Jadwal</a>
                        {% if owner == user %}
                            <form action="{% url 'dashboard:hapusJadwal' schedule.url %}" method="POST" style="display: inline;">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-danger"><b>Hapus</b></button>
                            </form>
                        {% endif %}
                    </div>
                </div>
                {% endfor %}
            </div>
        {% else %}
            <h1>Jadwal Tidak Ada</h1>
        {% endif %}
        <a class="btn btn-info m-3" href="{% url 'jadwal:buat-jadwal' %}"><b>Buat Rapat Baru</b></a>
    </div>
</div>
{% endblock content %}